on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed directories
        id: changed-directories
        uses: tj-actions/changed-files@v39.2.1
        with:
          files_ignore: ".github"
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_root: true
      - name: Use changed directories
        run: |
          DIRS=${{ steps.changed-files.outputs.all_changed_files }}
          for DIR in $DIRS; do
            echo $DIR
          done
